tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-container": "#c6c4c4",
                "surface-container-high": "#e8e8e8",
                "inverse-surface": "#2f3131",
                "on-tertiary-fixed-variant": "#474747",
                "tertiary-fixed": "#e4e2e1",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed": "#1b1c1c",
                "secondary-container": "#e2dfde",
                "on-secondary-container": "#636262",
                "on-primary-container": "#3d5900",
                "error": "#ba1a1a",
                "surface-dim": "#dadada",
                "background": "#f9f9f9",
                "primary": "#476800",
                "surface": "#f9f9f9",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#c8c6c6",
                "on-primary-fixed": "#131f00",
                "surface-bright": "#f9f9f9",
                "on-background": "#1a1c1c",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#515151",
                "inverse-primary": "#99d907",
                "error-container": "#ffdad6",
                "on-surface": "#1a1c1c",
                "outline": "#737a63",
                "primary-fixed": "#b4f734",
                "secondary-fixed-dim": "#c8c6c5",
                "surface-tint": "#476800",
                "on-secondary-fixed": "#1c1b1b",
                "on-secondary-fixed-variant": "#474746",
                "outline-variant": "#c2caaf",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e2e2e2",
                "inverse-on-surface": "#f1f1f1",
                "concrete-gray": "#D1D5DB",
                "on-primary": "#ffffff",
                "primary-fixed-dim": "#99d907",
                "on-primary-fixed-variant": "#354e00",
                "surface-variant": "#e2e2e2",
                "on-surface-variant": "#424935",
                "secondary-fixed": "#e5e2e1",
                "surface-container": "#eeeeee",
                "high-vis-white": "#FFFFFF",
                "asphalt-black": "#1A1A1A",
                "on-error": "#ffffff",
                "safety-green": "#97D700",
                "secondary": "#5f5e5e",
                "tertiary": "#5f5e5e",
                "surface-container-low": "#f3f3f3",
                "primary-container": "#97d700"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "unit": "8px",
                "container-max": "1280px",
                "section-gap": "96px",
                "margin-mobile": "16px",
                "gutter": "24px"
            },
            "fontFamily": {
                "label-md": ["Inter"],
                "display-lg": ["Montserrat"],
                "headline-lg-mobile": ["Montserrat"],
                "caption": ["Inter"],
                "headline-lg": ["Montserrat"],
                "body-lg": ["Inter"],
                "headline-md": ["Montserrat"],
                "body-md": ["Inter"]
            },
            "fontSize": {
                "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
                "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
                "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
            }
        },
    },
}
